version: '3'

services:
  oracle11g:
    container_name: oracle11g_test
    image: "wnameless/oracle-xe-11g:16.04"
    volumes:
      - /Users/alejandro/Proyectos/mquerydb:/u01/app/oracle
    restart: always
    ports:
     - "1521:1521"
     - "8081:8080"